USE [master]
GO
/****** Object:  Database [HommieStore]    Script Date: 6/30/2023 8:08:41 PM ******/
CREATE DATABASE [HommieStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HommieStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLEXPRESS2019\MSSQL\DATA\HommieStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HommieStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLEXPRESS2019\MSSQL\DATA\HommieStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [HommieStore] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HommieStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HommieStore] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HommieStore] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HommieStore] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HommieStore] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HommieStore] SET ARITHABORT OFF 
GO
ALTER DATABASE [HommieStore] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [HommieStore] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HommieStore] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HommieStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HommieStore] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HommieStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HommieStore] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HommieStore] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HommieStore] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HommieStore] SET  ENABLE_BROKER 
GO
ALTER DATABASE [HommieStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HommieStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HommieStore] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HommieStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HommieStore] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HommieStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HommieStore] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HommieStore] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [HommieStore] SET  MULTI_USER 
GO
ALTER DATABASE [HommieStore] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HommieStore] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HommieStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HommieStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HommieStore] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [HommieStore] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [HommieStore] SET QUERY_STORE = OFF
GO
USE [HommieStore]
GO
/****** Object:  Table [dbo].[Cart]    Script Date: 6/30/2023 8:08:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cart](
	[ID] [int] NOT NULL,
	[Username] [varchar](45) NOT NULL,
	[ProductID] [int] NULL,
	[Quantity] [int] NULL,
	[LastUpdatedTime] [datetime] NULL,
 CONSTRAINT [PK_tblcart] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 6/30/2023 8:08:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_tblcategory] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Order]    Script Date: 6/30/2023 8:08:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](45) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Phone] [varchar](20) NOT NULL,
	[Address] [nvarchar](400) NOT NULL,
	[OrderTime] [datetime] NULL,
	[Message] [nvarchar](400) NULL,
	[ShippingFee] [float] NULL,
	[Status] [varchar](20) NULL,
	[Comment] [nvarchar](200) NULL,
	[LastUpdatedTime] [datetime] NULL,
 CONSTRAINT [PK_tblorder] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderDetail]    Script Date: 6/30/2023 8:08:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderDetail](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[OrderID] [int] NULL,
	[ProductID] [int] NULL,
	[Price] [float] NULL,
	[Quantity] [int] NULL,
 CONSTRAINT [PK_tblorder_detail] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 6/30/2023 8:08:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
	[Description] [nvarchar](400) NULL,
	[Quantity] [int] NOT NULL,
	[Price] [float] NOT NULL,
	[CategoryID] [int] NULL,
	[Avatar] [varchar](5000) NULL,
	[Status] [tinyint] NOT NULL,
 CONSTRAINT [PK_tblproduct] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 6/30/2023 8:08:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Username] [varchar](45) NOT NULL,
	[Email] [varchar](320) NOT NULL,
	[Role] [varchar](10) NOT NULL,
	[Password] [varchar](59) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Gender] [tinyint] NULL,
	[Phone] [varchar](20) NULL,
	[Yob] [int] NULL,
	[Address] [nvarchar](400) NULL,
	[Avatar] [varchar](1000) NULL,
	[Enabled] [tinyint] NULL,
 CONSTRAINT [PK_user] PRIMARY KEY CLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[User] ADD  CONSTRAINT [DF_User_enabled]  DEFAULT ((1)) FOR [Enabled]
GO
ALTER TABLE [dbo].[Cart]  WITH CHECK ADD  CONSTRAINT [FK_Cart_Product] FOREIGN KEY([ProductID])
REFERENCES [dbo].[Product] ([ID])
GO
ALTER TABLE [dbo].[Cart] CHECK CONSTRAINT [FK_Cart_Product]
GO
ALTER TABLE [dbo].[Cart]  WITH CHECK ADD  CONSTRAINT [FK_Cart_User] FOREIGN KEY([Username])
REFERENCES [dbo].[User] ([Username])
GO
ALTER TABLE [dbo].[Cart] CHECK CONSTRAINT [FK_Cart_User]
GO
ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_Orders_User] FOREIGN KEY([Username])
REFERENCES [dbo].[User] ([Username])
GO
ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_Orders_User]
GO
ALTER TABLE [dbo].[OrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetail_Orders] FOREIGN KEY([OrderID])
REFERENCES [dbo].[Order] ([ID])
GO
ALTER TABLE [dbo].[OrderDetail] CHECK CONSTRAINT [FK_OrderDetail_Orders]
GO
ALTER TABLE [dbo].[OrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetail_Product] FOREIGN KEY([ProductID])
REFERENCES [dbo].[Product] ([ID])
GO
ALTER TABLE [dbo].[OrderDetail] CHECK CONSTRAINT [FK_OrderDetail_Product]
GO
ALTER TABLE [dbo].[Product]  WITH CHECK ADD  CONSTRAINT [FK_Product_Category] FOREIGN KEY([CategoryID])
REFERENCES [dbo].[Category] ([ID])
GO
ALTER TABLE [dbo].[Product] CHECK CONSTRAINT [FK_Product_Category]
GO
USE [master]
GO
ALTER DATABASE [HommieStore] SET  READ_WRITE 
GO
